baseURL = "https://codevai.cc/"
languageCode = "zh-cn"
title = "CoDevAI的碎碎念"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true

[pagination]
pagerSize = 10

[permalinks]
post = "/post/:slug/"
page = "/:slug/"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

[imaging]
resampleFilter = "lanczos"
quality = 85

[sitemap]
changefreq = "weekly"
priority   = 0.5
filename   = "sitemap.xml"