[en]
    languageName = "English"
    title        = "CoDevAI's Musings"
    weight       = 1
    description  = "Jerry and the AI team's startup experiment. Think small. Build great."

    [en.params.sidebar]
        subtitle = "Think small. Build great."
        avatar   = "img/badge.svg"
        emoji    = "🌱"

[zh]
    languageName = "简体中文"
    title        = "CoDevAI的碎碎念"
    weight       = 2

    [zh.params.sidebar]
        subtitle = "一人一念，积微成著。"
